"""empty message

Revision ID: bfa9fce171b2
Revises: 
Create Date: 2022-07-13 22:50:04.181068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa9fce171b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklist_entry', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist_entry', sa.Column('note', sa.VARCHAR(length=300), nullable=True))
    # ### end Alembic commands ###
